# Site settings
title: Code & Cappuccinos
header-img: img/backpack.png
email: brittny.lapierre@gmail.com
copyright_name: Code & Cappuccinos
description: "A blog with an author who loves to code, and drink cappuccinos."
baseurl: ""
url: "http://blog.codeandcappuccinos.com/"
twitter_username: "@codeandcapps"
instagram_username: codeandcappas
github_username:  l3rittny
facebook_username:  Brittny Lapierre
email_username:  "brittny.lapierre@gmail.com"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
